// <auto-generated /
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "داستان"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "شعر"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "فلسفه"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "جامعه شناسی"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "تئاتر"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "سینما"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "هنر"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "عکاسی"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "معماری"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "جستار"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
